# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WebService-Bloglines
version:      0.11
version_from: lib/WebService/Bloglines.pm
installdirs:  site
requires:
    LWP:                           0
    Test::More:                    0.32
    XML::Liberal:                  0.02
    XML::RSS::LibXML:              0.09

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
