# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WebService-Bloglines
version:      0.05
version_from: lib/WebService/Bloglines.pm
installdirs:  site
requires:
    LWP:                           0
    Test::More:                    0.32
    XML::RSS:                      0
    XML::XPath:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
